### ISSUE TITLE
Uploading files stopped working!

### ISSUE THREAD

**Issue by 3LOK** [GoogleCloudPlatform/gcloud-node#428] opened 2015-03-05 15:57 UTC
We use your library with automatic uploading. It started failing 15 minutes ago.

The error is "Invalid Credentials". Credentials have not changed. Tried renewing credentials, it did not help as well. Our code hasn't changed at all during that time, it just suddenly stopped working.

**Comment by stephenplusplus** [comment] 2015-03-05 17:31
@jgeewax

**Comment by stephenplusplus** [comment] 2015-03-05 17:32
We also haven't released any new code since our release before Christmas. Sounds like an account issue.

**Comment by ryanseys** [comment] 2015-03-05 20:13
What authentication method are you using?

**Comment by ryanseys** [comment] 2015-03-05 20:22
I know Google was having some issues with their SSO approximately 4-5 hours ago, so this might be the root cause. Also, App Engine and Google APIs were having issues around that time. You can see the problem on the (newly released!) Google Cloud Status website:

https://status.cloud.google.com/incident/appengine/15006

Closing as I strongly believe this is the root cause of your issue.

**Closed by ryanseys** 2015-03-05 20:22 UTC
