### ISSUE TITLE
grpc session timeout

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/gcloud-node#1267] opened 2016-04-26 21:57 UTC
I'm using `gcloud-node` v0.31.0 to read entities from Google Cloud Datastore.

I've deployed each step of our Node.js Bookshelf Getting Started app to App Engine. I run system tests against these deployed apps that exercise the apps' APIs. In particular some of my tests are doing `POST /api/books` which makes the server do `datastore.save(entity, ...)` on the backend.

If the apps have been idle for a few minutes (received no requests), then the very first `grpc` call initiated by a previously idle app will fail:
![screen shot 2016-04-26 at 2 46 01 pm](https://cloud.githubusercontent.com/assets/1213510/14835257/b0f67ec4-0bbd-11e6-92ed-f2e9f859644f.png)

I can reliably reproduce this behavior by letting an app sit idle for a few minutes, then trying to do something. The first grpc call will fail.

Here's an example:

```
> nodejs-getting-started@1.0.0 mocha /Users/jdobry/projects/nodejs-getting-started
> mocha test/index.js -t 30000 "--grep" "api.js"

  Bookshelf app
    2-structured-data/
      books/
        api.js
          1) should create a book
          ✓ should list books (2087ms)
          2) should delete a book
    3-binary-data/
      books/
        api.js
          3) should create a book
          ✓ should list books (2093ms)
          4) should delete a book
    4-auth/
      books/
        api.js
          5) should create a book
          ✓ should list books (2131ms)
          6) should delete a book
    5-logging/
      books/
        api.js
          7) should create a book
          ✓ should list books (2222ms)
          8) should delete a book
    6-pubsub/
      books/
        api.js
          9) should create a book
          ✓ should list books (2099ms)
          10) should delete a book
    7-gce/
      books/
        api.js
          11) should create a book
          ✓ should list books (2109ms)
          12) should delete a book


  6 passing (21s)
  12 failing
```
The first test in each test subgroup fails because it's the first grpc call being made by an idle app. The next test in each test subgroup succeeds because by the time the second test runs grpc has refreshed its connection. If I immediately re-run the tests:

```
> nodejs-getting-started@1.0.0 mocha /Users/jdobry/projects/nodejs-getting-started
> mocha test/index.js -t 30000 "--grep" "api.js"

  Bookshelf app
    2-structured-data/
      books/
        api.js
          ✓ should create a book (302ms)
          ✓ should list books (2091ms)
          ✓ should delete a book (125ms)
    3-binary-data/
      books/
        api.js
          ✓ should create a book (323ms)
          ✓ should list books (2098ms)
          ✓ should delete a book (100ms)
    4-auth/
      books/
        api.js
          ✓ should create a book (305ms)
          ✓ should list books (2109ms)
          ✓ should delete a book (316ms)
    5-logging/
      books/
        api.js
          ✓ should create a book (373ms)
          ✓ should list books (2116ms)
          ✓ should delete a book (238ms)
    6-pubsub/
      books/
        api.js
          ✓ should create a book (241ms)
          ✓ should list books (2088ms)
          ✓ should delete a book (202ms)
    7-gce/
      books/
        api.js
          ✓ should create a book (391ms)
          ✓ should list books (2232ms)
          ✓ should delete a book (185ms)

  18 passing (22s)
```
Everything works. If I wait a few minutes and re-run the tests, the first grpc calls will fail and I can find grpc timeout errors in the apps' logs in the Cloud Console.

When visiting one of these idle apps in the browser, the app will appear broken when it is first visited after being idle. Refresh the page and everything's back to normal, as grpc has fixed itself.

**Comment by stephenplusplus** [comment] 2016-04-26 22:07
I believe this is a duplicate of #1265 -- as it stands, we are awaiting some input from the gRPC team.

**Closed by stephenplusplus** 2016-04-26 22:07 UTC
