### ISSUE TITLE
gcloud is spamming my stderr

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/gcloud-node#1301] opened 2016-05-09 21:52 UTC
![image](https://cloud.githubusercontent.com/assets/534619/15125645/cfb30a1a-15e2-11e6-8bd8-05fcdba03adb.png)

I have an app that makes heavy use of pub/sub, vision api, and storage:
https://github.com/JustinBeckwith/cloudcats

If I let it sit idle for a while, it starts spamming my stderr with goaway errors:

```
D0509 14:32:55.418468000 123145306058752 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
D0509 14:34:24.583132000 123145307668480 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
D0509 14:35:54.334432000 123145306595328 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
D0509 14:37:23.608541000 123145307131904 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
D0509 14:38:52.921070000 123145306058752 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
```

**Comment by JustinBeckwith** [comment] 2016-05-09 21:53
@matthewloring since we were chatting about this

**Comment by matthewloring** [comment] 2016-05-09 21:58
Appears to be coming from the transport layer of grpc: https://github.com/grpc/grpc/blob/c236a213ee10f549d328840bc21c307eedd4b545/src/core/ext/transport/chttp2/transport/chttp2_transport.c#L698

**Comment by stephenplusplus** [comment] 2016-05-09 22:04
Duplicate of https://github.com/GoogleCloudPlatform/gcloud-node/issues/1204

Current status is we're waiting on 0.14 of grpc to be released.

**Comment by callmehiphop** [comment] 2016-05-09 22:04
I think this is a gRPC quirk, if an open channel idles for a few minutes, subsequent requests will fail with a `got goaway` error. However, after a single failed request, gRPC corrects itself everything will go back to normal, that is, until the channel idles again.

**Closed by stephenplusplus** 2016-05-09 22:04 UTC

**Comment by stephenplusplus** [comment] 2016-05-09 22:05
Oops, is this not a duplicate?

**Comment by callmehiphop** [comment] 2016-05-09 22:13
The error and steps to reproduce are the same as described in #1265, but this is the first time anyone reported the error itself being printed out.

**Comment by JustinBeckwith** [comment] 2016-05-10 04:19
I'd prefer to keep this open until we're sure there is a solution coming :)

**Comment by stephenplusplus** [comment] 2016-05-10 04:27
It's the same as we are tracking in #1204. The excessive output comes in a variety of flavors, this being one of them. It was reported originally here: https://github.com/grpc/grpc/issues/5967#issuecomment-204460329

We even have a PR ready for when the new gRPC release lands: https://github.com/GoogleCloudPlatform/gcloud-node/pull/1288

Nobody is more excited for that day than me :)

**Comment by JustinBeckwith** [comment] 2016-05-10 04:30
Much appreciated folks.  Thanks!

**Comment by 1N50MN14** [comment] 2016-05-10 22:57
+1 I'm getting the above (periodically) as well as a log of Service URL and Bearer, it's spamming my console as I'm using PubSub which keeps pulling... and logging! ;)
