### ISSUE TITLE
[Feature] gcloud-logging

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/gcloud-node#842] opened 2015-09-01 20:13 UTC
Is there any plan to include logging api in this package? If so what is the expected timeline?

Link: https://cloud.google.com/logging/docs/api/gcloud-logging

**Comment by jgeewax** [comment] 2015-09-01 20:26
PR's are welcome ! :)

Seriously though -- I think @stephenplusplus may be able to help answer....?

**Comment by stephenplusplus** [comment] 2015-09-01 20:51
I think the next two APIs we want to implement are [Resource Manager](https://cloud.google.com/resource-manager/reference/rest/index) and logging. A rough guess is probably an ETA of early-Mid October for both. PRs definitely welcome to speed up the process :)

**Comment by VikramTiwari** [comment] 2015-09-01 20:53
@jgeewax @stephenplusplus There's already some work going on with [trace](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs), I am guessing that they will also include logs in the lib once everything is stable on the core api end. Best will be have that whole lib included in this project.

As for PRs, step 0 - forking done! :+1: :)

**Comment by stephenplusplus** [comment] 2015-09-04 15:10
Awesome, keep us posted! Feel free to send a PR whenever you have something ready to discuss or get feedback on; don't worry about waiting until it's perfect. I'll tackle [supporting Resource Manager](#851) first, but feel free to ping me for any help with logging.

Thanks for helping!

**Comment by stephenplusplus** [comment] 2015-09-15 15:55
@VikramTiwari I'm getting started on this. I'll hopefully have a preliminary PR up for review in a couple days.

**Comment by VikramTiwari** [comment] 2015-09-15 16:29
@stephenplusplus Aha! Nice. :smile:  Sorry but i have been busy hence couldn't contribute anything.

**Comment by stephenplusplus** [comment] 2015-09-15 16:30
No problem at all! Just make sure to leave some time to test it out for us :)

**Comment by VikramTiwari** [comment] 2015-09-15 16:31
haha Alrighty! Committed for that. :)

**Comment by stephenplusplus** [comment] 2015-09-15 19:40
@jgeewax running into "The caller does not have permission" API errors while testing my Logging implementation. Specifically, it's a call to https://cloud.google.com/logging/docs/api/ref/rest/v1beta3/projects.sinks/create -- I'm guessing service accounts aren't sufficient for this API?

**Comment by jgeewax** [comment] 2015-09-16 04:12
@munangst : Does projects.sinks/create require 3LO? Or can a service account do that?

**Comment by munangst** [comment] 2015-09-16 13:13
The issue is that sinks.create (and also sinks.delete, sinks.update, and logs.delete) requires the caller to be a project owner, and service accounts can't be owners. Our expectation was that typically these operations are infrequent (since they set up long-lived log export destinations) and users would perform them manually as an admin using gcloud or the Developers Console. However, we've gotten some recent feedback that users want to manage log sinks with service accounts (e.g., to allow automation to set up new projects) so we're reconsidering this. We're also planning to support [Cloud IAM](https://cloud.google.com/iam) policies in the future so that you can manage permissions at a level finer than Project Viewer/Editor/Owner.

Can you explain a bit more about the use case? Is it feasible to pass the user's credentials for this operation instead of using a service account?

**Comment by stephenplusplus** [comment] 2015-09-16 15:44
I can't come up with a specific use case, but in general our library make the upstream APIs available for any of our users to easily fit into theirs. We do run into these one-off/bootstrap procedures from time to time that are best done with a UI (Pub/Sub creating a topic, Storage creating a bucket). In this case, since our library has full support for Storage, and a possible sink can be a bucket, if a user *did* have a need for programmatic creation of a sink, we can simplify the connection between a new sink and a Bucket destination:

```js
var gcloud = require('gcloud')({
  projectId: 'my-project-id',
  keyFilename: 'path-to-service-account-keyfile.json'
});

var storage = gcloud.storage();
var logging = gcloud.logging();

logging.createSink('new-sink-name', {
  destination: storage.bucket('logging')
}, function(err, sink) {});
```

Internally, that would grant the logging account as an owner on the bucket, create the sink, and give the user programmatic access to make further modifications to the sink (getting/setting metadata, deleting).

@jgeewax might be able to speak to specific use cases.

--

> Is it feasible to pass the user's credentials for this operation instead of using a service account?

As far as I know, this would be pretty tricky. In production, a user would be using our library headlessly, so I'm not sure how the user auth process would begin. This could just be due to my still-maturing familiarity with all of the auth options, so if anyone can explain how we can easily get the credentials we need, please correct me.

**Comment by jgeewax** [comment] 2015-09-20 12:26
> Is it feasible to pass the user's credentials for this operation instead of using a service account?

It really should be...

For example, the resource manager API only works with user account credentials... so this should look like

```
$ gcloud auth login
$ node myscript.js
```

And myscript should use the user-creds .... Do we really not do that anywhere in our auth situation?

**Comment by stephenplusplus** [comment] 2015-09-20 12:40
> Do we really not do that anywhere in our auth situation?

We do via https://github.com/google/google-auth-library-nodejs. We get a token successfully this way, and pass it with the request. The response is still "The caller does not have permission" -- does this mean I'm getting a token that doesn't work? Or maybe my project/account needs to be whitelisted?

**Comment by jgeewax** [comment] 2015-09-20 12:41
Or it's pulling credentials from the wrong place? 

It should work just fine with your credentials coming from `gcloud auth login`

**Comment by stephenplusplus** [comment] 2015-09-20 13:03
I had the error wrong, I'm getting "The caller does not have permission" with the service account and "Uncaught Error: Insufficient Permission" with `gcloud auth login`.

It seems to be picking them up from the right spot, because if I `gcloud auth revoke`, google-auth-library fails to get a token: "Error: invalid_grant"

**Comment by jgeewax** [comment] 2015-09-20 13:04
Can you execute the API request using the demo thing in the docs pages
(where you flip the slider to login wiht OAuth2?

**Comment by stephenplusplus** [comment] 2015-09-20 13:06
Yes.

**Comment by jgeewax** [comment] 2015-09-20 13:08
Yea that's really weird then... @munangst? Any ideas?

**Comment by stephenplusplus** [comment] 2015-09-20 13:24
Note that this is similar to https://github.com/GoogleCloudPlatform/gcloud-node/issues/864#issuecomment-140791410

**Comment by stephenplusplus** [comment] 2015-09-20 15:16
@callmehiphop want to give this a shot to see if it's just me? Basically run the system test code from my PR for creating a sink. Make sure you override the auth for the test and provide only a projectId. If you need help getting set up let me know.

**Comment by stephenplusplus** [comment] 2015-09-21 19:09
Is it possible falling back to the gcloud sdk token doesn't work here because it doesn't request the scopes needed for this API? (nothing about Logging or the all encompassing `auth/cloud-platform` scope).

<img width="442" alt="screen shot 2015-09-21 at 3 07 38 pm" src="https://cloud.githubusercontent.com/assets/723048/10001999/aaee0840-6072-11e5-8145-21e27e1dfbeb.png">

**Comment by callmehiphop** [comment] 2015-09-21 21:45
I also received a `Insufficient Permission` error

**Comment by stephenplusplus** [comment] 2015-10-06 19:30
@jgeewax another whitelisting issue, maybe. My project ID is nth-circlet-705.

**Comment by jgeewax** [comment] 2015-10-20 12:29
Just FYI, pinged the team, waiting to see what they say

**Comment by filipjs** [comment] 2015-10-20 13:28
Yes, we need the "cloud-platform" scope to work.

**Comment by stephenplusplus** [comment] 2015-10-20 13:30
Sorry for the late update, but I actually later confirmed `gcloud-platform` is included in the scopes requested by `gcloud auth login`.

**Comment by filipjs** [comment] 2015-10-20 13:53
Did you mean "cloud" not "gcloud"? 
I checked our backend, and it looks like those requests are not getting to us, meaning they are rejected earlier.

**Comment by stephenplusplus** [comment] 2015-10-20 14:23
Yes, sorry the `auth/cloud-platform` scope is requested by `gcloud auth login`.

After some playing around, I was able to create a sink successfully. As you predicted, @filipjs, an intermediary request was getting the error. I'll look into that and open an issue for it if necessary, but it's not one that relates to Logging.

Thanks for your help!

**Comment by filipjs** [comment] 2015-10-20 14:33
Great!
Also a note about that PR. Code there is creating a "project" sink, so it is probably a good idea to add some filter to it, otherwise it will match all entries from the whole project (see "filter" field name)
https://cloud.google.com/logging/docs/api/ref/rest/v1beta3/projects.logServices.sinks#LogSink
https://cloud.google.com/logging/docs/view/advanced_filters

We also have "log sinks" and "service sinks" but those are going away.

**Comment by stephenplusplus** [comment] 2015-10-20 14:52
Good call, and thanks for checking it out! Is there an API update coming soon? If there are any docs available or a changelog you can send over (sawchuk@gmail.com), that'd be helpful.

Also, if you don't mind, I'll give you another ping when the PR is closer to completion, but feel free to stay involved as much as you can as it evolves.

**Comment by munangst** [comment] 2015-10-20 15:14
Yes, we're working on some changes that will be released as v2 of the API.
We don't have any docs or changelog available yet because the new API
version hasn't been released yet -- contact us at
cloud-logging-feedback@google.com if you're interested in testing the new
API before it's publicly launched. We'll also ping this thread when the new
API version is available.

The main difference relevant to this issue is that we're simplifying the
way log sinks are specified. We'll be deprecating log-level sinks
(projects.logs.sinks) and service-level sinks (projects.logServices.sinks)
and keeping only project-level sinks (projects.sinks). You can send logs
from only a specific log or a specific service to a given project-level
sink with the "filter" sink property (using the syntax documented on
https://cloud.google.com/logging/docs/view/advanced_filters). For example,
the log-level sink "/projects/my-project/logs/syslog/sinks/my-sink" in
v1beta3 is equivalent to the project-level sink
"/projects/my-project/sinks/my-sink" with a filter expression
[log="syslog"].

>

**Comment by munangst** [comment] 2015-10-20 15:17
(Also, not to fear, we'll transparently migrate any pre-existing log-level
or service-level sinks to project-level sinks at some point after the v2
API is released.)

**Comment by stephenplusplus** [comment] 2015-11-30 16:29
To anyone interested, support for Logging in gcloud-node is ready for review. It would be great if you could check out [our API docs](https://stephenplusplus.github.io/gcloud-node/#/docs/master/logging) and leave any comments on the PR: #865. Thanks!

**Comment by JustinBeckwith** [comment] 2015-11-30 16:35
So this is based on the v1 logging API, right?  So we don't need to worry about whitelisting?

**Comment by stephenplusplus** [comment] 2015-11-30 16:51
All correct :)

**Closed** 2015-12-21 21:30 UTC
Labels: logging
