### ISSUE TITLE
cloud logging example is misleading where labels.instance_id has to be STRING

### ISSUE THREAD

**Issue by faithseed** [GoogleCloudPlatform/gcloud-node#1238] opened 2016-04-15 23:41 UTC
The doc says string for instance_id

var resource = {
  type: 'gce_instance',
  labels: {
    zone: 'global',
    instance_id: 3
  }
};

yet in practice, you will hit the following if you pass an int. ugh...

 { [ApiError: Invalid value at 'entries[0].resource.labels[0].value' (TYPE_STRING), 1]
  errors: undefined,
  code: 400,
  response: undefined,
  message: 'Invalid value at \'entries[0].resource.labels[0].value\' (TYPE_STRING), 1' }

**Comment by stephenplusplus** [comment] 2016-04-16 01:31
Can you show the code you're using? The code from the readme works for me.

Also, which version of gcloud-node are you running?

**Comment by faithseed** [comment] 2016-04-16 02:22
We use:
"gcloud": "0.28.0",

  resource = {
      type: 'gce_instance',
      labels: {
         instance_id: instance_id,
         zone: zone
      }
   };

   log.write([ logEntry ], function (err, apiResponse) {
         if (err) {
            logger.error(err);
         }
      });

**Comment by faithseed** [comment] 2016-04-16 02:33
https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/LogEntry

also this say labels are string?

labels	map (key: string, value: string)

**Comment by stephenplusplus** [comment] 2016-04-16 18:20
I was able to reproduce. Thanks for catching this. Any chance you'd be willing to send a PR with the fix for the docs?

**Comment by faithseed** [comment] 2016-04-18 16:24
sure, will do

**Comment by stephenplusplus** [comment] 2016-04-19 11:14
Fixed by #1241

**Closed by stephenplusplus** 2016-04-19 11:14 UTC
Labels: docs, logging
