### ISSUE TITLE
Looks like the build is broken?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#377] opened 2015-02-03 14:20 UTC
Either that or the badge is broken... Can someone take a look today?

**Comment by stephenplusplus** [comment] 2015-02-03 14:35
Usually, re-building will make the tests pass again.

The tests that fails are PubSub ones:

[1) pubsub Subscription should be able to pull and ack:](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/regression/pubsub.js#L175)
```sh
Uncaught Error: The subscription has no more messages available (subscription="/subscriptions/long-door-651/sub1").
      at handleResp (/home/travis/build/GoogleCloudPlatform/gcloud-node/lib/common/util.js:9:4160)
      at Request._callback (/home/travis/build/GoogleCloudPlatform/gcloud-node/lib/common/util.js:9:12797)
      at Request.self.callback (/home/travis/build/GoogleCloudPlatform/gcloud-node/node_modules/request/request.js:373:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/travis/build/GoogleCloudPlatform/gcloud-node/node_modules/request/request.js:1318:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/home/travis/build/GoogleCloudPlatform/gcloud-node/node_modules/request/request.js:1266:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)
```

[2) pubsub Subscription should receive the published message:](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/regression/pubsub.js#L184)
```sh
Uncaught Error: The subscription has no more messages available (subscription="/subscriptions/long-door-651/sub1").
      at handleResp (/home/travis/build/GoogleCloudPlatform/gcloud-node/lib/common/util.js:9:4160)
      at Request._callback (/home/travis/build/GoogleCloudPlatform/gcloud-node/lib/common/util.js:9:12797)
      at Request.self.callback (/home/travis/build/GoogleCloudPlatform/gcloud-node/node_modules/request/request.js:373:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/travis/build/GoogleCloudPlatform/gcloud-node/node_modules/request/request.js:1318:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/home/travis/build/GoogleCloudPlatform/gcloud-node/node_modules/request/request.js:1266:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:442:13)
```

I believe the premise of the issue is the messages aren't published in time for the call to receive them. We've had issues with these tests since we added support for PubSub, and have always attributed them to the alpha status of the upstream API. I'm not sure if there's something we can do in the tests / code to insure this doesn't happen, given that it works half of the time. Maybe something simple like setting a timeout in the tests to give the message time to process?

// @ryanseys

**Comment by tmatsuo** [comment] 2015-02-03 14:58
I'm pretty sure that it's related to: https://code.google.com/p/cloud-pubsub/issues/detail?id=5

The workaround is to publish multiple messages.
I don't think the gcloud golang has the same flakiness:
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/pubsub/integration_test.go

It uses the new batch interface (publishBatch[1] and pullBatch[2]) for the integration test with 10 messages and it works much better. It still fails sometimes, but it's because of the general 503 error, not because of the issue above.

FYI, the next version will only provide batch interfaces, and we recommend that everyone use the batch interface even for now.

[1]: https://cloud.google.com/pubsub/v1beta1/topics/publishBatch
[2]: https://cloud.google.com/pubsub/v1beta1/subscriptions/pullBatch

**Comment by tmatsuo** [comment] 2015-02-03 14:59
adding @rakyll for her experience

**Comment by stephenplusplus** [comment] 2015-02-03 15:15
Nice, we should probably implement a `publishBatch` method here, and then use that for the test.

**Comment by stephenplusplus** [comment] 2015-02-04 17:17
Closing this in favor of #379 - the plan is taking gcloud-go's solution and implementing publishBatch and pullBatch. If a better idea from anyone comes to light, feel free to add a comment.

**Closed by stephenplusplus** 2015-02-04 17:17 UTC
Labels: bug, core, pubsub, testing
