### ISSUE TITLE
SyntaxError on authentication command

### ISSUE THREAD

**Issue by leo-one** [GoogleCloudPlatform/gcloud-node#1387] opened 2016-06-16 04:01 UTC
The simple code below throws a SyntaxError.

```javascript
var fs = require('fs');

var googleCloudAuthFile = __dirname + '/google_cloud_auth.json';
fs.accessSync(googleCloudAuthFile, fs.F_OK);

var gcloud = require('gcloud')({
  projectId: 'project-id',
  keyFilename: googleCloudAuthFile
});
```

```
/vagrant/parse/city-chat-web/node_modules/readable-stream/lib/_stream_readable.js:117
};
 ^

SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/vagrant/parse/city-chat-web/node_modules/readable-stream/readable.js:6:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by leo-one** [comment] 2016-06-16 04:24
I created a empty project with only gcloud-node installed and the authentication worked. It also successfully made a safeSearch request.

I think that the error in this issue can be an conflict with other package. The package of the real project are:
```javascript
"dependencies": {
    "apn": "^1.7.5",
    "async": "^1.5.2",
    "express": "^4.13.4",
    "gcloud": "^0.36.0",
    "node-gcm": "^0.14.3",
    "parse-server": "^2.1.6",
    "request": "^2.69.0"
  }
```

**Comment by stephenplusplus** [comment] 2016-06-16 16:15
The code from the first post worked for me. Is it possible to get a sample repo that I can clone to see the failure? The details of the Vagrant VM and how Node was installed might be relevant as well.

**Comment by leo-one** [comment] 2016-06-20 03:55
@stephenplusplus If you run the same code with the dependences listed above, you'll see the error.
Please declare those dependences in package.json and run npm install. Then run the code.
The version of the Node.js is 5.5.0 and it was installed through Node Version Manager (https://github.com/creationix/nvm).

**Comment by stephenplusplus** [comment] 2016-06-20 12:43
I've tried this, but the script still executes normally.

**Comment by stephenplusplus** [comment] 2016-06-22 11:46
@leo-one try Node's stable release, v6.

**Comment by stephenplusplus** [comment] 2016-06-27 13:16
I'm going to close this out since I can't reproduce. I don't believe this is an issue with our library, but something environment-specific. If you're still stuck, feel free to keep sharing, and I'll gladly help however I can.

**Closed by stephenplusplus** 2016-06-27 13:16 UTC
