### ISSUE TITLE
Local Datastore problems since version 0.30.0

### ISSUE THREAD

**Issue by susanlinsfu** [GoogleCloudPlatform/gcloud-node#1220] opened 2016-04-09 05:56 UTC
Using a version prior to version 0.30.0 everything worked. This is how I would insert a record into my local datastore:

```
var projectId = process.env.DATASTORE_PROJECT_ID;
var host = process.env.DATASTORE_EMULATOR_HOST;
var gcloud = require('gcloud');

var datastore = gcloud.datastore;
var dataset = datastore.dataset({
  projectId: projectId,
  apiEndpoint: host
});

var key = dataset.key('Company');
dataset.save({
  key: key,
  data: {
    rating: '10'
  }
}, function(err) {
  console.log(key.path); // [ 'Company', 5669468231434240 ]
  console.log(key.namespace); // undefined
});
```

The record would show up in the datastore.

I then updated to version 0.30.0 (tried also the newest and the same issue occurred). When I try to connect and insert/get (any operation) an entity I am unable to. I get the following error from my nodejs console:

> E0408 22:51:33.856966404   39870 parsing.c:472]              Unknown frame type 50

The code I am using to insert records for 0.30.0+ is:

```
var projectId = process.env.DATASTORE_PROJECT_ID;
var host = process.env.DATASTORE_EMULATOR_HOST;

var gcloud = require('gcloud')({
  projectId: projectId
});

var datastore = gcloud.datastore({
    apiEndpoint: host
});

var key = datastore.key('Company');
datastore.save({
  key: key,
  data: {
    rating: '10'
  }
}, function(err) {
  console.log(key.path); // [ 'Company', 5669468231434240 ]
  console.log(key.namespace); // undefined
});  
```

`My local datastore was installed today using the command gcloud components install gcd-eumulator so it is the version as of April/8th/2016.`

I tried this on two separate environments (Ubuntu 15.04 and Windows 10) and the same error was occurring for environments.

**Comment by stephenplusplus** [comment] 2016-04-09 12:26
See the [Important things](https://github.com/GoogleCloudPlatform/gcloud-node/releases/tag/v0.30.0) section from the release notes.

@pcostell is there any documentation around using the gcd.sh emulator?

**Comment by dhermes** [comment] 2016-04-09 14:53
We just went through this in `gcloud-python`. The issue is the path contains an extra `datastore`. I'm AFK but will try to get you the PR where I fixed it

**Comment by dhermes** [comment] 2016-04-09 14:53
https://github.com/GoogleCloudPlatform/gcloud-python/pull/1709

**Comment by stephenplusplus** [comment] 2016-04-09 14:57
Oh, cool. Thanks! Will this work with the gcloud SDK emulator or is the gcd.sh still required?

**Comment by pcostell** [comment] 2016-04-09 16:03
IIRC, node uses gRPC, right?

gRPC is not built into the emulator that ships with the gcloud command line
tool. I'm working on getting all of this fixed, but until then people can
use a special gRPC only gcd.sh tool:
https://storage.googleapis.com/gcd/tools/gcd-grpc-1.0.0.zip

**Comment by stephenplusplus** [comment] 2016-04-09 16:04
We do use gRPC, yes. I was just wondering if there was any documentation that we can point folks to after they download the .sh file.

**Comment by pcostell** [comment] 2016-04-09 16:06
Ah sorry didn't see the important not sections. You still need the special
tool, but you shouldn't have to mess with the path like anyone using
proto-over-http.

Sorry, we are working on either better docs and getting it into gcloud CLI,
but it is moving slower than expected.

**Comment by stephenplusplus** [comment] 2016-04-09 16:08
No problem, thanks for clarifying.

@susanlinsfu I'm going to close the issue, but if you run into any issues using the gcd.sh emulator, feel free to ask any questions here.

**Closed by stephenplusplus** 2016-04-09 16:08 UTC
Labels: datastore, question

**Comment by susanlinsfu** [comment] 2016-04-09 16:39
Thanks. I got it running with gcd.sh tool and it is working now, but noticed there is no admin tool? I ran http://localhost:8080/_ah/admin and nothing was found. Does the admin console exist with this tool?

Cheers

**Comment by pcostell** [comment] 2016-04-09 16:49
Unfortunately it does not yet have an admin page.

If you need it, you *can* turn off gcd then point the version of gcd in the
emulator against your directory and use that viewer. They share the same
underlying data storage system, but you shouldn't run them at the same time
as they will likely try to over we rite each other.

Some technical background: the old gcd.sh tool (and in fact the production
v1beta2 system) was built on top of App Engine. Because of this, we were
able to just expose the App Engine local development admin console that you
could use to access your Datastore. The new version of gch.sh is a complete
rewrite, which means it should be much smaller and faster than the old
version (which needed most of the App Engine sdk to run). But it also means
we also need to rewrite these admin features.
-Patrick

**Comment by susanlinsfu** [comment] 2016-04-09 16:50
Thank you for the explanation!
