### ISSUE TITLE
1500 characters limit of a property?

### ISSUE THREAD

**Issue by seymores** [GoogleCloudPlatform/gcloud-node#1350] opened 2016-06-01 05:50 UTC
Hi,

I am getting error when I try to save a property with a long text -- to be precise more than 1500 characters. 
The entity saved fine when I reduced the string char count to be 1500 characters and below.
Anything above 1500 char count will throw me this error:
```
... code: 400, metadata: Metadata { _internal_repr: {} } }
```

I understand appengine has this limitation but the documentation says a text property can have up to 2mb of data so there must be something wrong here.

Using gcloud version 0.32.0.

**Comment by stephenplusplus** [comment] 2016-06-01 11:41
I believe this is a duplicate of #1091. If so, try:

```js
datastore.save({
  key: key,
  data: [
    {
      name: 'theLongStringPropertyName',
      value: 'The looooong string',
      excludeFromIndexes: true
    }
  ]
}, function() {})
```

**Closed** 2016-06-01 18:24 UTC
Labels: datastore, question
