### ISSUE TITLE
Many secs lag between subscription and first message

### ISSUE THREAD

**Issue by pierre-b** [GoogleCloudPlatform/gcloud-node#526] opened 2015-05-04 15:32 UTC
Hi, 

I experience many seconds lag between opening a subscription and receving the first message, then following messages are coming live...

Anyone else has same issue ?

Thanks

**Comment by ryanseys** [comment] 2015-05-17 19:59
Could this be as a result of the authentication requests that takes place on the first request? Once a token is retrieved from the API, all subsequent requests use that token and are more responsive and "real time".

**Comment by pierre-b** [comment] 2015-05-18 10:36
Hard to guess, I can see the successful subscription callback and have to wait around 30 sec to see the first message delivered... then it flows. Looks like pubsub takes time to route messages to new subscriptions ?

**Comment by ryanseys** [comment] 2015-05-19 20:52
Yeah that sounds like an issue not on our library's end. Have you tried to reproduce with another library, such as [`googleapis`](https://github.com/google/google-api-nodejs-client)

**Comment by pierre-b** [comment] 2015-05-20 14:29
Sorry I didn't have time to try it with another lib or tech, maybe we can wait to see if someone else experienced the same issue ?

**Comment by ryanseys** [comment] 2015-05-20 14:37
I can't see our library introducing that much lag for that request specifically.

**Comment by ryanseys** [comment] 2015-05-20 14:37
I will keep it open for now.

**Comment by callmehiphop** [comment] 2015-07-28 18:24
Closing because this sounds like an issue upstream and we haven't really heard any noise around it. Please re-open if needed!

**Closed by callmehiphop** 2015-07-28 18:24 UTC
Labels: pubsub
