### ISSUE TITLE
Transaction.save does not allow a NULL value.

### ISSUE THREAD

**Issue by krisnye** [GoogleCloudPlatform/gcloud-node#1081] opened 2016-01-21 01:53 UTC
Null is a perfectly valid value to insert into the datastore and should be supported by this API.  Null indicates that the value is not present, but that it still needs to be indexed, and so it is different from simply not having a property which means the entity will not be indexed for that property.

When attempting to save a record with a null value this exception is thrown:

      throw new Error('Unsupported field value, ' + v + ', is provided.');
            ^
    Error: Unsupported field value, null, is provided.
        at Object.valueToProperty (gcloud/lib/datastore/entity.js:437:9)
        at gcloud/lib/datastore/request.js:405:29
        at gcloud/lib/datastore/request.js:404:48
        at Transaction.DatastoreRequest.save (gcloud/lib/datastore/request.js:397:12)
        at gcloud/lib/datastore/transaction.js:229:42
        at Transaction.commit_ (gcloud/lib/datastore/transaction.js:225:6)
        at /Users/krisnye/Projects/glass/lib/googlecloud/Dataset.js:343:21

**Comment by krisnye** [comment] 2016-01-21 02:23
Ok, I found a fix for this, it's incredibly simple.  In datastore/entity.js, simply encode a null value as {stringValue:null}

Old code

  if (v instanceof String || typeof v === 'string') {
    p.string_value = v;
    return p;
  }

New code

  if (v == null || v instanceof String || typeof v === 'string') {
    p.string_value = v;
    return p;
  }

**Comment by stephenplusplus** [comment] 2016-01-21 18:52
Duplicate of #1022. Sadly, we're a bit stuck until the next version of Datastore is released, v1beta3.

**Closed by stephenplusplus** 2016-01-21 18:52 UTC
